---
output: 
  html_document
css: styles.css
runtime: shiny
---

# Seagrass transect training {.tabset}
  
```{r setup, message = F, warning = F, results = 'hide', echo = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F, echo = F, fig.path = 'figs/', fig.path = 'figures/')

library(tidyverse)
library(seagrasstransect)
# devtools::load_all()
library(shiny)
library(reactable)
library(mapview)

# for leaflet map
data(trnlns)
data(trnpts)

monagncy <- trnlns %>% 
  select(TRAN_ID = Site , MonAgency) %>% 
  sf::st_set_geometry(NULL)

trnpts <- trnpts %>% 
  left_join(monagncy, by = 'TRAN_ID') %>% 
  unite('lonlat', LONG_DD, LAT_DD, sep = ',') %>% 
  unite('lab', TRANSECT, lonlat, sep = ': ') %>% 
  mutate(lab = paste0('Transect: ', lab))

# get data and format
trnjsn <- read_trnjsn()
dat <- form_trnjsn(trnjsn)

# get choices for selection
sppopt <- unique(dat$Savspecies)

downloadButtonRmd <- function (outputId, label, class = NULL, ...)  {
  tags$a(id = outputId, class = paste("btn btn-default shiny-download-link", 
                                      class), href = "", target = "_blank", download = NA, 
         icon("download"), label, ...)
}

# metric summary
datsum <- dat %>% 
  dplyr::mutate(
    grp = paste0(MonitoringAgency, ' (', Crew, ')')
  ) %>% 
  group_by(Site, Savspecies, var) %>% 
  summarise(cv = 100 * sd(aveval, na.rm = T) / mean(aveval, na.rm = T)) %>% 
  ungroup %>% 
  na.omit()

psum <- ggplot(datsum, aes(x = Site, y = var, fill = cv)) +
  facet_wrap(~Savspecies, ncol  = 2) + 
  scale_x_discrete(expand = c(0, 0)) + 
  scale_y_discrete(expand = c(0, 0)) +
  geom_tile(colour = 'black') + 
  scale_fill_gradientn('CV %', colours = c('lightgreen', 'tomato1')) + 
  theme_bw() + 
  theme(
    strip.background = element_blank(), 
    # panel.background = element_blank(), 
    panel.grid = element_blank(), 
    axis.title.y = element_blank()
  ) + 
  labs(
    subtitle = "Metric variation among sites and species", 
    caption = 'CV is st. dev. / mean that captures differences among crews'
  )

# # style file
# styles <- readLines('https://raw.githubusercontent.com/tbep-tech/css-styling/master/styles.css')
# writeLines(styles, 'styles.css')
```


```{r downloadhandlers}
# wq data
output$dlfigs <- downloadHandler(
  filename = function(){'allfigures.pdf'},
  content = function(file){

    todl <- dat %>% 
      select(Savspecies, var, Site) %>% 
      unique %>% 
      arrange(Savspecies, var, Site)

    pdf(file, width = input$width, height = input$height)
    
    for(i in 1:nrow(todl)){
      
      site <- todl[[i, 'Site']]
      species <- todl[[i, 'Savspecies']]
      varplo <- todl[[i, 'var']]
      
      p <- show_compplot(dat, site, species, varplo)
      
      print(p)
      
    }
      
    dev.off()
    
  }
)
```

```{r reactives}
plodat <- reactive({
  
  # inputs
  sppsel <- input$sppsel
  sitsel <- input$sitsel
  varsel <- input$varsel
  
  req(varsel)
  
  out <- show_compplot(dat, sitsel, sppsel, varsel, base_size = 18, xtxt = 13)
  
  return(out)
  
})
```

## Plot results {.tabset .tabset-pills}

```{r}
column(12, 
  column(4, selectInput('sppsel', 'Select species:', choices = sppopt)),
  column(4,
    renderUI({
      
      # inputs
      sppsel <- input$sppsel

      tosel <- dat %>% 
        filter(Savspecies %in% sppsel) %>% 
        pull(Site) %>% 
        unique %>% 
        sort
      
      selectInput('sitsel', 'Select site:', choices = tosel)
      
    })
  ),
  column(4, 
    renderUI({
      
      # inputs
      sppsel <- input$sppsel
      sitsel <- input$sitsel
      
      req(sitsel)
  

      tosel <- dat %>% 
        filter(Savspecies %in% sppsel) %>% 
        filter(Site %in% sitsel) %>% 
        pull(var) %>%  
        unique
      
      selectInput('varsel', 'Select variable:', choices =  tosel)
            
    })     
  )

)
```

### Individual 

```{r, fig.align = 'center'}
output$plo <- renderPlot(plodat(), height = 600, width = 850)
plotOutput('plo')
```

### Summary

```{r, fig.align = 'center', height = 6.5, width = 8}
psum
```


## Crew inventory

```{r}
totab <- dat %>% 
  select(`Montoring Agency` = MonitoringAgency, Crew) %>% 
  unique

reactable(totab, 
  groupBy = 'Montoring Agency',
  defaultColDef = colDef(
    footerStyle = list(fontWeight = "bold"),
    resizable = TRUE
    ),
  columns = list(
    Crew = colDef(aggregated = JS("
      function(cellInfo) {
        // Get comma-separated list of unique values in visible rows
        var values = cellInfo.subRows.map(function(row) { return row.Crew })
        var unique = values.reduce(function(obj, v) { obj[v] = true; return obj }, {})
        return Object.keys(unique).join(', ')
      }
    ")
    )
  ),
  filterable = T, 
  bordered = T
)
```

## Transect locations

```{r, out.width = '100%'}
mapview(trnpts, label = trnpts$lab, zcol = 'MonAgency', lwd = 0, legend = F) + 
  mapview(trnlns, zcol = 'MonAgency', homebutton = F, layer.name = 'Monitoring Agency', lwd = 4)
```

## Download 

```{r}
column(6,  
  HTML('<br></br>'),
  downloadButtonRmd('dlfigs', 'Download all figures'),
  HTML('<br></br>'),
  numericInput('height', 'Plot heights (in)', value = 7, min = 0, step = 1),
  numericInput('width', 'Plot widths (in)', value = 8, min = 0, step = 1)
)
```

