---
output: 
  html_document
css: styles.css
runtime: shiny
---
  
```{r message = F, warning = F, echo = F}
knitr::opts_chunk$set(echo = F, warning = F, message = F, fig.path = 'figures/')

library(tbeptools)
library(tidyverse)
library(lubridate)
library(plotly)
library(htmltools)
library(shiny)
library(mapview)
library(leaflet)
library(sf)
library(extrafont)
library(EnvStats)
library(leafsync)

source('R/funcs.R')

data(trnpts)
data(tbsegshed)
data(covest)
data(algdat)
data(allann)

loadfonts(device = 'pdf', quiet = T)
if(Sys.info()[1] == 'Windows')
  loadfonts(device = 'win', quiet = T)

fml <- 'Lato Light'

otbshed <- tbsegshed %>% 
  filter(bay_segment %in% 'OTB')
otbpts <- trnpts[otbshed, ]

wqstat <- stations %>% 
  filter(bay_segment %in% 'OTB')

epcdata <- epcdata %>% 
  filter(yr >= 1998) %>% 
  mutate(
    sd_q = case_when(
      is.na(sd_q) ~ T, 
      !is.na(sd_q) ~ F
    )
  )

# for factor levels
algnms <- c('Bacillariophyta', 'Cyanobacteria', 'Karenia brevis', 'Pseudo-nitzschia pungens', 'Pseudo-nitzschia sp.', 'Pyrodinium bahamense', 'Tripos hircus', 'other')
cols <- pal_alg(algnms)
names(cols) <- algnms
savnms <- c('AA', 'DA', 'Halodule', 'Thalassia', 'Syringodium', 'Ruppia', 'Halophila spp.')

# names for map comparison selection
names(algnms) <- algnms
wqalgnms <- c(list('tn' = 'tn', 'chla' = 'chla', 'secchi' = 'sd_raw_m', 'salinity' = 'Sal_Mid_ppth'), as.list(algnms))

# minor theme tweaks
pthm <- theme(
    axis.text.x = element_text(size = 11, angle = 45, hjust = 1),
    legend.text = element_text(size = 12), 
    axis.title.y = element_text(size = 12),
    text = element_text(fml), 
    legend.position = 'top',
    # panel.grid.minor=element_blank(),
    # panel.grid.major=element_blank(),
    panel.background = element_rect(fill = '#ECECEC')
    ) 

# base map
m <- mapview(otbpts, homebutton = F, layer.name = 'Transects', col.regions = 'darkgreen') +
  mapview(st_as_sf(wqstat, coords = c('Longitude', 'Latitude'), crs = st_crs(tbshed)), homebutton = F, layer.name = 'EPCHC stations', col.regions = 'darkblue') 
m <- m@map
```

```{r reactives}
mapsel <- reactive({
  
  # input
  trn <- input$trn
  wqst <- input$wqst
  
  trnpt <- otbpts %>% 
    filter(TRAN_ID %in% trn)
  
  wqstpt <- wqstat %>% 
    filter(epchc_station %in% wqst)
  
  out <- m %>% 
    clearMarkers() %>% 
    addCircles(data = trnpt, ~LONG_DD, ~LAT_DD, color = 'darkgreen', weight = 20) %>% 
    addCircles(data = wqstpt, ~Longitude, ~Latitude, color = 'darkblue', weight = 20) %>% 
    addLabelOnlyMarkers(data = otbpts, ~LONG_DD, ~LAT_DD, label = ~TRAN_ID, labelOptions = labelOptions(
      noHide = T, 
      direction = 'auto', 
      textOnly = T,
      textsize = '15px',
      style = list(
        'color' = 'darkgreen'
      )
    )) %>% 
    addLabelOnlyMarkers(data = wqstat, ~Longitude, ~Latitude, label = ~epchc_station, labelOptions = labelOptions(
      noHide = T, 
      direction = 'auto', 
      textOnly = T,
      textsize = '15px',
      style = list(
        'color' = 'darkblue'
      )
    ))
  
  return(out)
  
})

# observed data plot
obsplo <- reactive({
  
  # input
  wqst <- input$wqst
  sgty <- input$sgty
  trn <- input$trn
  
  ##
  # data to plot
  
  # wq data
  wqplo <- epcdata %>% 
    filter(epchc_station %in% wqst) %>% 
    select(Date = SampleTime, sd_raw_m, sd_q, chla) %>% 
    mutate(Date = as.Date(Date))
  
  # algae data
  algplo <- algdat %>% 
    filter(epchc_station %in% wqst) %>% 
    group_by(yrqrt, name) %>%
    summarise(count = sum(count, na.rm = T)) %>% 
    ungroup %>% 
    mutate(
      name = factor(name, levels = algnms, labels = algnms)
      )

  # seagrass data
  sglab <- 'BB Abundance'
  sgval <- 'bbest'
  if(sgty == 'Freq. Occ.'){
    sglab <- 'Freq. Occ. (%)'
    sgval <- 'foest'
  }
  sgplo <- covest %>% 
    filter(Transect %in% trn) %>% 
    rename(val = !!sgval)
  
  ##
  # plots

  # chl plot
  p1 <- plot_ly(wqplo, x = ~Date, y = ~chla, name = 'Chlorophyll-a', type= 'scatter', mode = 'lines', line = list(color = '#427355')) %>% 
    layout(
      yaxis = list(title = 'Conc. (ug/L)'),
      xaxis = list(gridcolor = '#FFFFFF'),
      showlegend = T, 
      font = list(family = fml)
    )
  
  # secchi plot
  p2 <- plot_ly(wqplo, x = ~Date) %>% 
    add_trace(y = ~sd_raw_m, name = 'Secchi depth', type= 'scatter', mode = 'lines', line = list(color = '#0047FE')) %>% 
    layout(
      yaxis = list(title = 'Depth (m)'),
      xaxis = list(gridcolor = '#FFFFFF'),
      showlegend = T, 
      font = list(family = fml)
    )
  
  if(any(!wqplo$sd_q))
    p2 <- p2 %>% 
      add_trace(data = wqplo[!wqplo$sd_q, ], x = ~Date, y = ~sd_raw_m, name = 'Secchi on bottom', type = 'scatter', mode = 'marker', marker = list(color = "#FF6347", size = 8))
  
  # algae plot
  p3 <-  plot_ly(algplo, x = ~ yrqrt, y= ~count, color = ~name, text = ~paste0(name, ', ', yrqrt), hoverinfo = 'text') %>% 
    add_bars() %>% 
    layout(
      yaxis = list(title = 'Phyto. cell count (0.1/ml)', gridcolor = '#FFFFFF'),
      barmode = 'stack',
      showlegend = T, 
      font = list(family = fml)
    )
  
  # seagrass plot
  p4 <- plot_ly(sgplo, x = ~Date, y = ~val, color = ~Savspecies, stackgroup = 'one', type = 'scatter', mode = 'none') 
  if(sgty == 'Freq. Occ.')
      p4 <- plot_ly(sgplo, x = ~Date, y = ~val, color = ~Savspecies, stackgroup = 'one', type = 'scatter', mode = 'none', groupnorm = 'percent') 

  p4 <- p4 %>% 
    layout(
      yaxis = list(title = sglab),
      xaxis = list(title = NA, gridcolor = '#FFFFFF'),
      barmode = 'stack',
      showlegend = T, 
      legend = list(title = list(text = 'Seagrass')),
      shapes = vrtline_fun(sgplo, sgty)
    )

  out <- subplot(p3, p1, p2, p4, nrows = 4, shareX = T, titleY = T, which_layout = 1) %>%
    layout(
      # title = paste0('Station ', wqst, ', Transect ', trn),
      # legend = list(font = list(size = 16)), 
      yaxis = list(gridcolor = '#ECECEC'),
      font = list(family = fml),
      plot_bgcolor = '#FFFFFF'
    )
  
  return(out)
  
})

# trend estimates for selected years
trnds <- reactive({
  
  # input
  yrsl <- input$yrsl

  out <- allann %>% 
    filter(yr >= yrsl[1] & yr <= yrsl[2]) %>% 
    group_by(dat, station, var) %>% 
    nest %>% 
    mutate(
      trnd = purrr::map(data, function(data){
        
        knout <- try({kendallTrendTest(val ~ yr, data)})
                  
        if(inherits(knout, 'try-error') | nrow(data) < 2){
          out <- data.frame(n = NA, tau = NA, slope= NA, pval = NA)
          return(out)
        }
        
        outest <- round(knout$estimate, 2)
        outpval <- p_ast(knout$p.value)
        nval <- nrow(na.omit(data))
        out <- c(n = nval, outest, pval = outpval) %>%
          data.frame %>%
          t %>%
          data.frame %>%
          select(-intercept)
        return(out)
        
      })
    ) %>% 
    select(-data) %>% 
    unnest(trnd) %>% 
    na.omit() %>% 
    mutate(
      n = as.numeric(n),
      tau = as.numeric(tau), 
      slope = as.numeric(slope)
    )

  return(out)
  
})

# sg trend matrix
sgtrndplo <- reactive({
  
  # input
  trnds <- trnds()

  toplo <- trnds %>% 
    filter(dat %in% 'cov') %>% 
    mutate(var = factor(var, levels = rev(savnms)))

  p <- ggplot(toplo, aes(x = var, y = station, fill = tau)) + 
    geom_tile(colour = 'grey') +
    geom_text(aes(label = pval)) + 
    scale_x_discrete(expand = c(0, 0)) + 
    scale_y_discrete('Transect', expand = c(0, 0)) + 
    scale_fill_gradient2('Kendall tau', low = 'lightblue', mid = 'white', high = 'lightgreen') + 
    theme(
      axis.title.x = element_blank(),
      axis.text.x = element_text(angle = 30)
      )
  
  out <- ggplotly(p)

  return(out)
  
})

# wq trend matrix
wqtrndplo <- reactive({
  
  # input
  trnds <- trnds()

  toplo <- trnds %>% 
    filter(dat %in% 'epc') 

  p <- ggplot(toplo, aes(x = var, y = station, fill = tau)) + 
    geom_tile(colour = 'grey') +
    geom_text(aes(label = pval)) + 
    scale_x_discrete(expand = c(0, 0)) + 
    scale_y_discrete('EPCHC station', expand = c(0, 0)) + 
    scale_fill_gradient2('Kendall tau', low = 'lightblue', mid = 'white', high = 'lightgreen') + 
    theme(
      axis.title.x = element_blank(),
      axis.text.x = element_text(angle = 30)
      )
  
  out <- ggplotly(p)

  return(out)
  
})

# phyto trend matrix
algtrndplo <- reactive({
  
  # input
  trnds <- trnds()

  toplo <- trnds %>% 
    filter(dat %in% 'alg') %>% 
    mutate(var = factor(var, levels = rev(algnms)))

  p <- ggplot(toplo, aes(x = var, y = station, fill = tau)) + 
    geom_tile(colour = 'grey') +
    geom_text(aes(label = pval)) + 
    scale_x_discrete(expand = c(0, 0)) + 
    scale_y_discrete('EPCHC station', expand = c(0, 0)) + 
    scale_fill_gradient2('Kendall tau', low = 'lightblue', mid = 'white', high = 'lightgreen') + 
    theme(
      axis.title.x = element_blank(), 
      panel.background = element_rect(color = 'white'), 
      axis.text.x = element_text(angle = 30)
      )
  
  out <- ggplotly(p)

  return(out)
  
})

# map trend selection
trndmapsel <- reactive({
  
  # input
  trnds <- trnds()
  sgvar1 <- input$sgvar1
  wqalgvar1 <- input$wqalgvar1
  sgvar2 <- input$sgvar2
  wqalgvar2 <- input$wqalgvar2

  
  trnds <- trnds %>% 
    mutate(
      sz = abs(tau), 
      sz = scales::rescale(sz, to= c(3, 15), from = c(0, 1)), 
      cols = ifelse(sign(tau) == -1, 'green', 'blue')
      )
  sgtrnd1 <- trnds %>% 
    filter(var %in% sgvar1) %>% 
    rename(TRAN_ID = station) %>% 
    left_join(., otbpts, by = 'TRAN_ID')
  wqalgtrnd1 <- trnds %>% 
    filter(var %in% wqalgvar1) %>% 
    rename(epchc_station = station) %>% 
    mutate(epchc_station = as.numeric(epchc_station)) %>% 
    left_join(., wqstat, by = 'epchc_station')
  sgtrnd2 <- trnds %>% 
    filter(var %in% sgvar2) %>% 
    rename(TRAN_ID = station) %>% 
    left_join(., otbpts, by = 'TRAN_ID')
  wqalgtrnd2 <- trnds %>% 
    filter(var %in% wqalgvar2) %>% 
    rename(epchc_station = station) %>% 
    mutate(epchc_station = as.numeric(epchc_station)) %>% 
    left_join(., wqstat, by = 'epchc_station')
  
  m1 <- m %>% 
    clearMarkers() %>% 
    clearControls() %>% 
    addCircleMarkers(data = sgtrnd1, ~LONG_DD, ~LAT_DD, fillOpacity = 0.5, fillColor = ~cols, radius = ~sz, stroke = F) %>% 
    addCircleMarkers(data = sgtrnd1, ~LONG_DD, ~LAT_DD, fillOpacity = 0, color = 'black', radius = ~sz, opacity = 1, weight = 2,
                     label = ~paste0('Transect: ', TRAN_ID, ', Tau: ', tau, ', p ', pval)) %>% 
    addCircleMarkers(data = wqalgtrnd1, ~Longitude, ~Latitude, fillOpacity = 0.5, fillColor = ~cols, radius = ~sz, stroke = F, 
                     label = ~paste0('Station: ', epchc_station, ', Tau: ', tau, ', p ', pval))
  
  m2 <- m %>% 
    clearMarkers() %>% 
    clearControls() %>% 
    addCircleMarkers(data = sgtrnd2, ~LONG_DD, ~LAT_DD, fillOpacity = 0.5, fillColor = ~cols, radius = ~sz, stroke = F) %>% 
    addCircleMarkers(data = sgtrnd2, ~LONG_DD, ~LAT_DD, fillOpacity = 0, color = 'black', radius = ~sz, opacity = 1, weight = 2,
                     label = ~paste0('Transect: ', TRAN_ID, ', Tau: ', tau, ', p ', pval)) %>% 
    addCircleMarkers(data = wqalgtrnd2, ~Longitude, ~Latitude, fillOpacity = 0.5, fillColor = ~cols, radius = ~sz, stroke = F,
                     label = ~paste0('Station: ', epchc_station, ', Tau: ', tau, ', p ', pval))
  
  out <- leafsync::sync(m1, m2, ncol = 2)
  
  return(out)
  
})
```

# Old Tampa Bay Seagrass evaluation {.tabset}

## Observed changes

```{r, out.width = '100%'}
output$mapsel <- renderLeaflet(mapsel())
leafletOutput('mapsel')
```

```{r}
column(12,
  column(4, selectInput('wqst', 'Select water quality station:', choices = sort(unique(wqstat$epchc_station)))), 
  column(4, selectInput('trn', 'Select transect:', choices = levels(covest$Transect))),
  column(4, selectInput('sgty', 'Select seagrass plot type:', choices = c('BB average', 'Freq. Occ.')))
)
```

<br>
<br>
<br>

```{r}
output$obsplo <- renderPlotly(obsplo())
plotlyOutput('obsplo', height = "1000px")
```

## Trends and correlations {.tabset .tabset-pills}

All analyses based on annual averages. 

```{r}
column(12, 
  column(6, sliderInput('yrsl', 'Select date range:', min = 1998, max = 2019, value = c(1998, 2019), sep = '', width = 600))
)
```

<br>
<br>
<br>

### Water quality

```{r}
output$wqtrndplo <- renderPlotly(wqtrndplo())
plotlyOutput('wqtrndplo', height = 600, width = 600)
```

### Phytoplankton

```{r}
output$algtrndplo <- renderPlotly(algtrndplo())
plotlyOutput('algtrndplo', height = 600, width = 600)
```

### Seagrass abundance

```{r}
output$sgtrndplo <- renderPlotly(sgtrndplo())
plotlyOutput('sgtrndplo', height = 600, width = 600)
```

### Maps

```{r}
output$trndmapsel <- renderUI(trndmapsel())
fillCol(
  flex = c(NA, 1),
  column(12,
    column(6, 
      selectInput('sgvar1', 'Select seagrass map 1:', choices = savnms), 
      selectInput('wqalgvar1', 'Select wq/algae map 1:', choices = wqalgnms)
    ), 
    column(6, 
      selectInput('sgvar2', 'Select seagrass map 2:', choices = savnms), 
      selectInput('wqalgvar2', 'Select wq/algae map 2:', choices = wqalgnms)
    ),
  ),
  uiOutput('trndmapsel')
)
```

