on:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: "0 12 * * *"
    
name: build 

jobs:
  render:
    name: build
    runs-on: ubuntu-20.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
        with: 
          extra-repositories: 'https://fawda123.r-universe.dev'
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Setup R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with: 
          packages: |
            any::dplyr
            any::rmarkdown
            any::knitr
            any::tidyr
            any::extrafont
            any::flextable
            tbeptools
      - name: Build water atlas content
        run: Rscript -e 'source("wateratlas_source.R")'
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git commit -m 'Re-build data and create content' || echo "No changes to commit"
          git push origin || echo "No changes to commit"